/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedConfirmRouteImport } from './routes/_authed/confirm'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedTicketsIndexRouteImport } from './routes/_authed/tickets/index'
import { Route as AuthedMarketplaceIndexRouteImport } from './routes/_authed/marketplace/index'
import { Route as AuthedEventsIndexRouteImport } from './routes/_authed/events/index'
import { Route as AuthedTicketsTicketIdRouteImport } from './routes/_authed/tickets/$ticketId'
import { Route as AuthedMarketplaceEventIdRouteImport } from './routes/_authed/marketplace/$eventId'
import { Route as AuthedEventsNewRouteImport } from './routes/_authed/events/new'
import { Route as AuthedEventsEventIdRouteImport } from './routes/_authed/events/$eventId'
import { Route as AuthedCheckoutEventIdRouteImport } from './routes/_authed/checkout/$eventId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConfirmRoute = AuthedConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedTicketsIndexRoute = AuthedTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMarketplaceIndexRoute = AuthedMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventsIndexRoute = AuthedEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTicketsTicketIdRoute = AuthedTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMarketplaceEventIdRoute =
  AuthedMarketplaceEventIdRouteImport.update({
    id: '/marketplace/$eventId',
    path: '/marketplace/$eventId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEventsNewRoute = AuthedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventsEventIdRoute = AuthedEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckoutEventIdRoute = AuthedCheckoutEventIdRouteImport.update({
  id: '/checkout/$eventId',
  path: '/checkout/$eventId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/confirm': typeof AuthedConfirmRoute
  '/checkout/$eventId': typeof AuthedCheckoutEventIdRoute
  '/events/$eventId': typeof AuthedEventsEventIdRoute
  '/events/new': typeof AuthedEventsNewRoute
  '/marketplace/$eventId': typeof AuthedMarketplaceEventIdRoute
  '/tickets/$ticketId': typeof AuthedTicketsTicketIdRoute
  '/events/': typeof AuthedEventsIndexRoute
  '/marketplace/': typeof AuthedMarketplaceIndexRoute
  '/tickets/': typeof AuthedTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/confirm': typeof AuthedConfirmRoute
  '/checkout/$eventId': typeof AuthedCheckoutEventIdRoute
  '/events/$eventId': typeof AuthedEventsEventIdRoute
  '/events/new': typeof AuthedEventsNewRoute
  '/marketplace/$eventId': typeof AuthedMarketplaceEventIdRoute
  '/tickets/$ticketId': typeof AuthedTicketsTicketIdRoute
  '/events': typeof AuthedEventsIndexRoute
  '/marketplace': typeof AuthedMarketplaceIndexRoute
  '/tickets': typeof AuthedTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authed/confirm': typeof AuthedConfirmRoute
  '/_authed/checkout/$eventId': typeof AuthedCheckoutEventIdRoute
  '/_authed/events/$eventId': typeof AuthedEventsEventIdRoute
  '/_authed/events/new': typeof AuthedEventsNewRoute
  '/_authed/marketplace/$eventId': typeof AuthedMarketplaceEventIdRoute
  '/_authed/tickets/$ticketId': typeof AuthedTicketsTicketIdRoute
  '/_authed/events/': typeof AuthedEventsIndexRoute
  '/_authed/marketplace/': typeof AuthedMarketplaceIndexRoute
  '/_authed/tickets/': typeof AuthedTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/confirm'
    | '/checkout/$eventId'
    | '/events/$eventId'
    | '/events/new'
    | '/marketplace/$eventId'
    | '/tickets/$ticketId'
    | '/events/'
    | '/marketplace/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/confirm'
    | '/checkout/$eventId'
    | '/events/$eventId'
    | '/events/new'
    | '/marketplace/$eventId'
    | '/tickets/$ticketId'
    | '/events'
    | '/marketplace'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authed/confirm'
    | '/_authed/checkout/$eventId'
    | '/_authed/events/$eventId'
    | '/_authed/events/new'
    | '/_authed/marketplace/$eventId'
    | '/_authed/tickets/$ticketId'
    | '/_authed/events/'
    | '/_authed/marketplace/'
    | '/_authed/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/confirm': {
      id: '/_authed/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof AuthedConfirmRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/tickets/': {
      id: '/_authed/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthedTicketsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketplace/': {
      id: '/_authed/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthedMarketplaceIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/events/': {
      id: '/_authed/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthedEventsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tickets/$ticketId': {
      id: '/_authed/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthedTicketsTicketIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketplace/$eventId': {
      id: '/_authed/marketplace/$eventId'
      path: '/marketplace/$eventId'
      fullPath: '/marketplace/$eventId'
      preLoaderRoute: typeof AuthedMarketplaceEventIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/events/new': {
      id: '/_authed/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthedEventsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/events/$eventId': {
      id: '/_authed/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthedEventsEventIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkout/$eventId': {
      id: '/_authed/checkout/$eventId'
      path: '/checkout/$eventId'
      fullPath: '/checkout/$eventId'
      preLoaderRoute: typeof AuthedCheckoutEventIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedRouteChildren {
  AuthedConfirmRoute: typeof AuthedConfirmRoute
  AuthedCheckoutEventIdRoute: typeof AuthedCheckoutEventIdRoute
  AuthedEventsEventIdRoute: typeof AuthedEventsEventIdRoute
  AuthedEventsNewRoute: typeof AuthedEventsNewRoute
  AuthedMarketplaceEventIdRoute: typeof AuthedMarketplaceEventIdRoute
  AuthedTicketsTicketIdRoute: typeof AuthedTicketsTicketIdRoute
  AuthedEventsIndexRoute: typeof AuthedEventsIndexRoute
  AuthedMarketplaceIndexRoute: typeof AuthedMarketplaceIndexRoute
  AuthedTicketsIndexRoute: typeof AuthedTicketsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConfirmRoute: AuthedConfirmRoute,
  AuthedCheckoutEventIdRoute: AuthedCheckoutEventIdRoute,
  AuthedEventsEventIdRoute: AuthedEventsEventIdRoute,
  AuthedEventsNewRoute: AuthedEventsNewRoute,
  AuthedMarketplaceEventIdRoute: AuthedMarketplaceEventIdRoute,
  AuthedTicketsTicketIdRoute: AuthedTicketsTicketIdRoute,
  AuthedEventsIndexRoute: AuthedEventsIndexRoute,
  AuthedMarketplaceIndexRoute: AuthedMarketplaceIndexRoute,
  AuthedTicketsIndexRoute: AuthedTicketsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
